services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: nexcare_backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: nexcare_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true