export const SPECIALIZATIONS = [
    { label: "General Medicine", value: "general_medicine" },
    { label: "General Surgery", value: "general_surgery" },
    { label: "Pediatrics", value: "pediatrics" },
    { label: "Obstetrics & Gynecology", value: "obstetrics_gynecology" },
    { label: "Orthopedics", value: "orthopedics" },
    { label: "ENT (Otorhinolaryngology)", value: "ent" },
    { label: "Ophthalmology", value: "ophthalmology" },
    { label: "Dermatology", value: "dermatology" },
    { label: "Psychiatry", value: "psychiatry" },
    { label: "Anesthesiology", value: "anesthesiology" },
    { label: "Radiology", value: "radiology" },
    { label: "Pathology", value: "pathology" },
    { label: "Microbiology", value: "microbiology" },
    { label: "Pharmacology", value: "pharmacology" },
    { label: "Community Medicine", value: "community_medicine" },
    { label: "Forensic Medicine", value: "forensic_medicine" },
    { label: "Emergency Medicine", value: "emergency_medicine" },
    { label: "Family Medicine", value: "family_medicine" },
    { label: "Respiratory Medicine", value: "respiratory_medicine" },
    { label: "Physical Medicine & Rehabilitation", value: "physical_medicine_rehab" },
    { label: "Nuclear Medicine", value: "nuclear_medicine" },
    { label: "Geriatrics", value: "geriatrics" },
    { label: "Cardiology", value: "cardiology" },
    { label: "Neurology", value: "neurology" },
    { label: "Gastroenterology", value: "gastroenterology" },
    { label: "Endocrinology", value: "endocrinology" },
    { label: "Nephrology", value: "nephrology" },
    { label: "Medical Oncology", value: "medical_oncology" },
    { label: "Clinical Hematology", value: "clinical_hematology" },
    { label: "Rheumatology", value: "rheumatology" },
    { label: "Clinical Immunology", value: "immunology" },
    { label: "Infectious Diseases", value: "infectious_diseases" },
    { label: "Critical Care Medicine", value: "critical_care_medicine" },
    { label: "Cardiothoracic Surgery", value: "cardiothoracic_surgery" },
    { label: "Neurosurgery", value: "neurosurgery" },
    { label: "Urology", value: "urology" },
    { label: "Plastic Surgery", value: "plastic_surgery" },
    { label: "Pediatric Surgery", value: "pediatric_surgery" },
    { label: "Vascular Surgery", value: "vascular_surgery" },
    { label: "Surgical Oncology", value: "surgical_oncology" },
    { label: "GI Surgery", value: "gastrointestinal_surgery" },
    { label: "Colorectal Surgery", value: "colorectal_surgery" },
    { label: "Hand Surgery", value: "hand_surgery" },
    { label: "Transplant Surgery", value: "transplant_surgery" },
    { label: "Pediatric Cardiology", value: "pediatric_cardiology" },
    { label: "Pediatric Neurology", value: "pediatric_neurology" },
    { label: "Pediatric Oncology", value: "pediatric_oncology" },
    { label: "Neonatology", value: "neonatology" },
    { label: "Pediatric Gastroenterology", value: "pediatric_gastroenterology" },
    { label: "Pediatric Nephrology", value: "pediatric_nephrology" },
    { label: "Interventional Radiology", value: "interventional_radiology" },
    { label: "Pain Medicine", value: "pain_medicine" },
    { label: "Sports Medicine", value: "sports_medicine" },
    { label: "Palliative Medicine", value: "palliative_medicine" },
    { label: "Sleep Medicine", value: "sleep_medicine" },
    { label: "Addiction Medicine", value: "addiction_medicine" },
    { label: "Reproductive Medicine", value: "reproductive_medicine" },
];

export const INDIAN_LANGUAGES = [
    // Major/Commonly Used
    { label: "English", value: "en" },
    { label: "Hindi", value: "hi" },
    { label: "Punjabi", value: "pa" },
    { label: "Bengali", value: "bn" },
    { label: "Marathi", value: "mr" },
    { label: "Telugu", value: "te" },
    { label: "Tamil", value: "ta" },
    { label: "Gujarati", value: "gu" },
    { label: "Urdu", value: "ur" },
    { label: "Kannada", value: "kn" },
    { label: "Odia", value: "or" },
    { label: "Malayalam", value: "ml" },
    // Official Scheduled Languages
    { label: "Assamese", value: "as" },
    { label: "Bodo", value: "brx" },
    { label: "Dogri", value: "doi" },
    { label: "Konkani", value: "kok" },
    { label: "Maithili", value: "mai" },
    { label: "Meitei (Manipuri)", value: "mni" },
    { label: "Nepali", value: "ne" },
    { label: "Santali", value: "sat" },
    { label: "Sindhi", value: "sd" },
    { label: "Kashmiri", value: "ks" },
    { label: "Sanskrit", value: "sa" },
];